config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :instructors
  
  resources :users, path: '/courses/users'
  resources :courses
  resources :lessons

  namespace :users do
    resources :enrollments
    resources :courses do
      resources :reviews
      collection do
        get 'in_progress'
      end
    end
  end

  root to: 'courses#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
	validates :name, presence: true
	validates :description, presence: true
	validates :price, presence: true
	belongs_to :instructor
	has_many :enrollments
	has_many :users, through: :enrollments
	has_many :user_course_reviews
	has_many :reviews, through: :user_course_reviews
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
	belongs_to :user
	belongs_to :course
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :courses
end

app/models/lesson.rb
class Lesson < ApplicationRecord
	
end

app/models/review.rb
class Review < ApplicationRecord
  has_many :users
  has_many :user_course_reviews
  has_many :courses, through: :user_course_reviews
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many :enrollments
  has_many :courses, through: :enrollments
  has_many :user_course_reviews
  has_many :reviews, through: :user_course_reviews
end

app/models/user_course_review.rb
class UserCourseReview < ApplicationRecord
  belongs_to :user
  belongs_to :course
  belongs_to :review
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_instructor!
  protected

  def after_sign_in_path_for(resource)
    if resource.is_a?(User)
      users_courses_path
    elsif resource.is_a?(Instructor)
      courses_path
    else
      super
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:edit, :update, :destroy, :show]

  def index
    @courses = current_instructor.courses
  end

  def show; end

  def new
    @course = Course.new
  end
  
  def create
    @course = Course.new(course_params)
    @course.instructor_id = current_instructor.id
    if @course.save    
      flash[:success] = "course successfully created"
      redirect_to courses_path
    else
      render 'new'
    end
  end
  
  def edit; end

  def update  
    if @course.update(course_params)
      redirect_to @course
    else
      render :edit
    end
  end

  def destroy
   @course.destroy

   redirect_to courses_path
  end

  private
  def course_params
    params.require(:course).permit(:name, :description, :price, :instructor_id)
  end

  def set_course
    @course = Course.find(params[:id])
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
	def index
		@lessons = Lesson.all
	end

	def show
		@lesson = Lesson.find(params[:id])
	end

	def new
		@lesson = Lesson.new
	end

	def create
		@lesson = @course.lessons.new(lesson_params)
		if @lesson.save
			redirect_to course_lesson_path(@course, @lesson)
    else
    	render :new
    end
	end

	def edit
		@lesson = Lesson.find(params[:id])
	end

	def update
		if @lesson.update(lesson_params)
      redirect_to course_lesson_path(@course, @lesson)
    else
      render :edit
    end
	end

	def destroy
		@lesson = Lesson.find(params[:id])
		@lesson.destroy
		redirect_to @course
	end
	
	private
	def set_course_and_lesson
		@course = Course.find(params[:course_id])
		@lesson = @course.lessons.find(params[:id])
	end
	
	def lesson_params
		params.require(:lesson).permit(:name, :description, :content)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
end

app/controllers/user_base_controller.rb
class UserBaseController < ApplicationController
  skip_before_action :authenticate_instructor!
end

app/controllers/users/courses_controller.rb
class Users::CoursesController < UserBaseController
  def index
   @courses = Course.where.not(id: current_user.enrollments.pluck(:course_id))
  end

  def in_progress
   @courses = current_user.courses
  end

  def show
    @course = Course.find(params[:id])
    @reviews = Review.where.not(id: current_user.reviews.pluck(:review_id))
    @review = @course.reviews.build()
  end

  def reviews;  end

  def destroy
    @review = current_user.reviews.find(params[:id])
    @review.destroy
    redirect_to users_course_path, notice: 'Review deleted successfully.'
  end

end

app/controllers/users/enrollments_controller.rb
class Users::EnrollmentsController < UserBaseController
  def index; end

  def create
   @enrollment = current_user.enrollments.new(course_id: params[:course_id])
   if @enrollment.save
    CourseMailer.with(user: current_user, course: @course).course_enrolled.deliver_now
    flash[:notice] = 'You enrolled successfully in the course'
   else
    flash[:alert] = 'Course enrollment failed'
   end
   redirect_to users_courses_path
  end

end

app/controllers/users/reviews_controller.rb
class Users::ReviewsController < UserBaseController
  def index
    @reviews = Review.where.not(id: current_user.reviews.pluck(:review_id))
  end

  def new
    @review = Review.new
  end

  def create
    @review = current_user.reviews.new(review_params)
   if @review.save
    flash[:notice] = 'Thanks for Review'
    redirect_to users_course_reviews_path
   else
    flash[:alert] = 'Review not added'
   end
   
  end

  private
  def review_params
    params.require(:review).permit(:rating, :comments, :course_id)
  end

end

app/views/courses/_form.html.erb
<h1>Add Course<h1>

<%= form_for @course  do |f| %>
  <div class="row mb-3">
    <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm"><%= f.label :name %></label>
    <div class="col-sm-3">
      <%= f.text_field :name, class: "form-control form-control-sm" %>
    </div>
  </div>

  <div class="row mb-3">
    <label for="colFormLabel" class="col-sm-2 col-form-label"><%= f.label :description %></label>
    <div class="col-sm-3">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg"><%= f.label :price %></label>
    <div class="col-sm-3">
      <%= f.text_field :price, class: "form-control form-control-lg"%>
    </div>
  </div>

  <div class="col-5">
    <button type="submit" class="btn btn-primary">Add Course</button>
  </div>
<% end %>

app/views/courses/edit.html.erb
<%= render 'form' %>

app/views/courses/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Price</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @courses.each_with_index do |course, index|%>
      <tr>
       <td><%= index + 1 %></td>
       <td><%= course.name %></td>
       <td><%= course.description %></td>
       <td><%= course.price %></td>
       <td><%= link_to "Edit", edit_course_path(course) %></td>
       <td><%= link_to "Show", course_path(course) %></td>
       <td><%= link_to "Destroy", course_path(course), data: { "turbo-method": :delete } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Add course", new_course_path %>

app/views/courses/new.html.erb
 <%= render 'form' %>

app/views/courses/show.html.erb
<div class= "container">
  <strong>Name:</strong>
  <%= @course.name %>
  <strong>Description:</strong>
  <%= @course.description %>
  <strong>price:</strong>
  <%= @course.price%>
 <%= link_to 'Back', courses_path %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <%= link_to 'E-learning', root_path, class: 'navbar-brand' %>
    </div>
  
   <% if instructor_signed_in? || user_signed_in?  %>
    <%= button_to "Sign out", destroy_instructor_session_path,  method: :delete, class: "btn btn-primary"%>
   <% else %>
    <%= link_to "Sign up", new_instructor_registration_path, class: "btn btn-primary" %>
    <%= link_to "Sign in", new_instructor_session_path, class: "btn btn-primary"%>
   <% end %>
	 
   <% if user_signed_in? %>
    <%= link_to "Enrolled Courses", in_progress_users_courses_path, class: "btn btn-primary" %>
    <%= link_to "Courses", users_courses_path, class: "btn btn-primary" %>
   <% else %>
   <% end %>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>

      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ELearning</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  </body>
</html>

app/views/lessons/_form.html.erb
<h1>Add Lesson<h1>

<%= form_for :lesson  do |f| %>
  <div class="row mb-3">
    <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm"><%= f.label :name %></label>
    <div class="col-sm-3">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="row mb-3">
    <label for="colFormLabel" class="col-sm-2 col-form-label"><%= f.label :description %></label>
    <div class="col-sm-3">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>

  <div class="row">
    <label for="colFormLabelLg" class="col-sm-2 col-form-label col-form-label-lg"><%= f.label :content %></label>
    <div class="col-sm-3">
      <%= f.text_field :content, class: "form-control"%>
    </div>
  </div>

  <div class="col-5">
    <button type="submit" class="btn btn-primary">Add Lesson</button>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<%= render "form" %>

app/views/lessons/index.html.erb
<table class="table">
	<thead>
		<tr>
			<th scope="col">#</th>
			<th scope="col">Name</th>
			<th scope="col">Description</th>
			<th scope="col">Content</th>
			<th scope="col">Action</th>
		</tr>
	</thead>
	<tbody>
		<% @lessons.each do |lesson|%>
			<tr>
				<th scope="row">1</th>
				<td><%= lesson.name%></td>
				<td><%= lesson.description%></td>
				<td><%= lesson.content%></td>
				<td><%= link_to "Edit", edit_lesson_path(lesson) %></td>
				<td><%= link_to "Show", lesson_path(lesson)%></td>
				<td><%= link_to "Destroy", lesson_path(lesson), data: { "turbo-method": :delete} %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<%= link_to "Add lesson", new_lesson_path %>

app/views/lessons/new.html.erb
<%= render "form" %>

app/views/lessons/show.html.erb
<div class="container">
<strong>Name:</strong>
<%= @lesson.name %>
<strong>Description:</strong>
<%= @lesson.description%>
<strong>Content:</strong>
<%= @lesson.content%>

<%= link_to 'back', lessons_path %>
</div>

app/views/pages/index.html.erb
<h1>Home Page<h1>

app/views/users/courses/_form.html.erb
 <%= form_for @course do |f| %>
    <%= f.fields_for :reviews  do |f| %>
     <div class="form-group">
      <%= f.label :rating %>
      <%= f.number_field(:rating, in: 1..5, class: "form-control" ) %>
     </div>

     <div class="form-group">
      <%= f.label :comments %>
      <%= f.text_area :comments, class: 'form-control' %>
     </div>

     <div class="col-sm-10 offset-sm-2">
     <button type="submit" class="btn btn-primary">Add review</button>
     </div>
    <% end %>
  <% end %>
  

app/views/users/courses/in_progress.html.erb
<div class="container">
<table class="table">
 <thead>
  <tr>
  <th scope="col">Name</th>
  <th scope="col">Description</th>
  <th scope="col">Price</th>
  <th scope="col">Action</th>
  </tr>
  </thead>
  <tbody>
  <% @courses.each do |course|%>
  <tr>
   <td><%= course.name %></td>
   <td><%= course.description %></td>
   <td><%= course.price %></td>
   <td><%= link_to "Show", users_course_path(course) %></td>
  </tr>
 <% end %>
 </tbody>
 </table>
</div>

app/views/users/courses/index.html.erb
<div class="container">
<table class="table">
 <thead>
  <tr>
   <th scope="col">Name</th>
   <th scope="col">Description</th>
   <th scope="col">Price</th>
   <th scope="col">Enrollment</th>
  </tr>
  </thead>
  <tbody>
  <% @courses.each do |course|%>
  <tr>
   <td><%= course.name %></td>
   <td><%= course.description %></td>
   <td><%= course.price %></td>
   <td><%= link_to "Enroll", users_enrollments_path(course_id: course.id), data: { "turbo-method": :post } %></td>
  </tr>
  <% end %>
  </tbody>
  </table>
</div>

app/views/users/courses/show.html.erb
<div class= "container">
  <strong>Name:</strong>
  <%= @course.name %>
  <strong>Description:</strong>
  <%= @course.description %>
  <strong>price:</strong>
  <%= @course.price%>
  <%= link_to 'Back', in_progress_users_courses_path %>
  <div class="container">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Rating</th>
          <th scope="col">Comment</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
      <% @reviews.each do |review|%>
          <tr>
          <td><%= review.rating %></td>
          <td><%= review.comments %></td>
          <td><%= link_to "Delete", users_course_path(@course), data: { "turbo-method": :delete } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <%= render 'form' %>

</div>  

app/views/users/reviews/_form.html.erb
<h1>Add Review<h1>

<%= form_for @review, url: users_course_reviews_path do |f| %>
  <div class="row mb-3">
    <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm"><%= f.label :rating %></label>
    <div class="col-sm-3">
      <%= f.number_field(:rating, in: 1..5, class: "form-control" ) %>
    </div>
  </div>

  <div class="row mb-3">
    <label for="colFormLabel" class="col-sm-2 col-form-label"><%= f.label :comment %></label>
    <div class="col-sm-3">
      <%= f.text_field :comments, class: "form-control" %>
    </div>
  </div>

  <div class="col-5">
    <button type="submit" class="btn btn-primary">Add review</button>
  </div>
<% end %>

app/views/users/reviews/index.html.erb
<div class="container">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Rating</th>
      <th scope="col">Comment</th>
    </tr>
  </thead>
  <tbody>
  <% @reviews.each do |review|%>
      <tr>
       <td><%= review.rating %></td>
       <td><%= review.comments %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Add review", new_users_course_review_path %>
</div>

app/views/users/reviews/new.html.erb
<%= render 'form' %>